### ISSUE TITLE
Redirect onomap url to map

### ISSUE THREAD

**Issue by gpetit** [Universite-Gustave-Eiffel/NoisePlanet#1]
We have to make a redirection of http://onomap.noise-planet.org/ to http://map.noise-planet.org/

Keep http://onomap.noise-planet.org/ alive for the moment.

**Comment by nicolas-f** [comment]
Ok. http://onomap.noise-planet.org may be down for a moment during the transition.

**Comment by gpetit** [comment]
No, don't stop http://onomap.noise-planet.org/. Just make a redirection ;-)

**Comment by nicolas-f** [comment]
I can redirect http://map.noise-planet.org to http://onomap.noise-planet.org without downtime but not the inverse.

**Comment by Picaut** [comment]
http://onomap.noise-planet.org
must be redirected to
http://noise-planet.org/map_noisecapture/index.html

Not necessary to create  http://map.noise-planet.org

**Comment by ebocher** [comment]
done
