### ISSUE TITLE
Export link to a map

### ISSUE THREAD

**Issue by Picaut** [Universite-Gustave-Eiffel/NoisePlanet#10]
When the user is on the map, it will be useful to obtain a link for the map, which can be shared.

**Comment by gpetit** [comment]
+1
We already talked about this with @ebocher ... he has an idea how to do it

**Comment by nicolas-f** [comment]
Would like to remove the iframe too.

**Comment by ebocher** [comment]
Do you to share a URL as we do here mapuce.orbisgis.org ?

**Comment by Picaut** [comment]
Yes. It is a good solution. However it could be more useful to give the link of the map, instead as of opening a new window with the corresponding link. One can also consider a sharing using social apps.

**Comment by nicolas-f** [comment]
The map hash url is now integrated. Solved
