### ISSUE TITLE
Replace time donut by bar chart graphs

### ISSUE THREAD

**Issue by nicolas-f** [Universite-Gustave-Eiffel/NoisePlanet#39]
So we have the choice between 3 bar charts (week, saturday, sunday) or 1 bar chart with 3 groups (https://jsfiddle.net/Loo5d9w5/15/)

**Comment by Picaut** [comment]
I prefer one graph per period (week, saturday, sunday). I think it show a more visible result

**Comment by nicolas-f** [comment]
I don't know if you want different colors on each bars ?

![out](https://user-images.githubusercontent.com/1382241/31540459-008e02ec-b00c-11e7-8654-691c9ccf04c6.gif)

**Comment by Picaut** [comment]
Yes. The color of each bar must be assigned in function of the corresponding noise level.

**Comment by nicolas-f** [comment]
With colors

![out](https://user-images.githubusercontent.com/1382241/31544440-188c34a4-b01b-11e7-83c8-81d6d73f2d07.gif)

**Comment by Picaut** [comment]
Perfect

**Comment by nicolas-f** [comment]
Done in #43
