### ISSUE TITLE
Add an information when NoiseCapture server is down

### ISSUE THREAD

**Issue by Picaut** [Universite-Gustave-Eiffel/NoisePlanet#81]
When NoiseCapture data server is down, no measurements are displayed on the map at http://noise-planet.org/map_noisecapture/ 
It should be important to have a message on the map displaying the fact that data are temporarily unavailable

**Comment by nicolas-f** [comment]
Something like that ?

![image](https://user-images.githubusercontent.com/1382241/84391102-ce52e680-abf8-11ea-8880-c64af2174c83.png)

**Comment by Picaut** [comment]
Exactly. Perfect.
